version: '3.8'

services:
  userservice:
    build:
      context: ./backend/userservice
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - sqlite-data:/app/dist/data
    networks:
      - transcendence

networks:
  transcendence:
    driver: bridge

volumes:
  sqlite-data:
