services:
    ssl-generator:
      container_name: ssl-generator
      build:
        context: .
        dockerfile: ssl-generator/Dockerfile
      networks:
        - bridge-network
      volumes:
        - ssl-certs:/etc/ssl
      restart: "no"

    auth-service:
      container_name: auth-service
      build:
        context: .
        dockerfile: backend/auth-service/Dockerfile
      ports:
        - "5000:5000"
      networks:
        - bridge-network
      env_file:
        - secrets/backend/auth-service/auth-service-secrets.txt
        - secrets/backend/common/common-secrets.txt
      volumes:
        - auth-service-db-data:/app/backend/auth-service/prisma
        - ssl-certs:/etc/ssl
      depends_on:
        - ssl-generator
      restart: always

    game-service:
      container_name: game-service
      build:
        context: .
        dockerfile: backend/game-service/Dockerfile
      ports:
        - "5001:5001"
      networks:
        - bridge-network
      env_file:
        - secrets/backend/game-service/game-service-secrets.txt
        - secrets/backend/common/common-secrets.txt
      volumes:
        - game-service-db-data:/app/data
        - ssl-certs:/etc/ssl
      depends_on:
        - ssl-generator
      restart: always

    user-service:
      container_name: user-service
      build:
        context: .
        dockerfile: backend/user-service/Dockerfile
      ports:
        - "5002:5002"
      networks:
        - bridge-network
      env_file:
        - secrets/backend/user-service/user-service-secrets.txt
        - secrets/backend/common/common-secrets.txt
      volumes:
        - user-service-db-data:/app/data
        - ssl-certs:/etc/ssl
      depends_on:
        - ssl-generator
      restart: always

    proxy-service:
      container_name: proxy-service
      build:
        context: .
        dockerfile: backend/proxy-service/Dockerfile
      ports:
        - "5003:5003"
      networks:
        - bridge-network
      env_file:
        - secrets/backend/proxy-service/proxy-service-secrets.txt
        - secrets/backend/common/common-secrets.txt
      volumes:
        - proxy-service-db-data:/example/path
        - ssl-certs:/etc/ssl
      depends_on:
        - auth-service
        - user-service
        - game-service
        - ssl-generator
      restart: always

    pong-service:
      container_name: pong-service
      build:
        context: .
        dockerfile: backend/pong-service/Dockerfile
      ports:
        - "5005:5005"
      networks:
        - bridge-network
      env_file:
        - secrets/backend/pong-service/pong-service-secrets.txt
        - secrets/backend/common/common-secrets.txt
      volumes:
        - pong-service-db-data:/example/path
        - ssl-certs:/etc/ssl
      depends_on:
        - ssl-generator
      restart: always

    frontend:
        container_name: frontend
        build:
          context: .
          dockerfile: frontend/Dockerfile
        ports:
          - "80:80"
          - "443:443"
        networks:
          - bridge-network
        volumes:
          - frontend-nginx-logs:/var/log/nginx
          - ssl-certs:/etc/ssl
        env_file:
          - secrets/frontend/frontend-secrets.txt
        depends_on:
          - proxy-service
          - ssl-generator
        restart: always

volumes:
  ssl-certs:
  auth-service-db-data:
  game-service-db-data:
  user-service-db-data:
  pong-service-db-data:
  proxy-service-db-data:
  frontend-nginx-logs:

networks:
  bridge-network:
    name: transcendence_bridge-network
