global:
  resolve_timeout: 1m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'slack-notifications'

receivers:
  - name: 'slack-notifications'
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/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'
        channel: '#prometheus-logs'
        send_resolved: true
        icon_url: https://avatars3.githubusercontent.com/u/3380462
        title: '{{ template "slack.default.title" . }}'
        text: '{{ template "slack.default.text" . }}'

templates:
  - '/etc/alertmanager/template/alert.tmpl'
