global:
  resolve_timeout: 1m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'slack-notifications'

receivers:
  - name: 'slack-notifications'
    slack_configs:
      - api_url: '$SLACK_HOOK_API_URL'
        channel: '#$CHANNEL_NAME'
        send_resolved: true
        icon_url: https://avatars3.githubusercontent.com/u/3380462
        title: '{{ template "slack.default.title" . }}'
        text: '{{ template "slack.default.text" . }}'

templates:
  - '/etc/alertmanager/template/alert.tmpl'
