services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ../../secrets/devops/grafana/grafana-secrets.txt
    networks:
      - bridge-network
    depends_on:
      - prometheus
    restart: always

  prometheus:
    build: ./prometheus
    container_name: prometheus
    volumes:
      - prometheus-data:/prometheus
    ports:
      - 9090:9090
    networks:
      - bridge-network
    depends_on:
      - alertmanager
    restart: always

  alertmanager:
    build: ./alertmanager
    container_name: alertmanager
    ports:
      - "9093:9093"
    env_file:
      - ../../secrets/devops/alertmanager/alertmanager-secrets.txt
    volumes:
      - alertmanager-data:/alertmanager
    networks:
      - bridge-network
    restart: always

  node_exporter:
    image: prom/node-exporter
    container_name: node_exporter
    ports:
      - "9100:9100"
    networks:
      - bridge-network
    restart: always

volumes:
  prometheus-data:
  alertmanager-data:

networks:
  bridge-network:
    name: transcendence_bridge-network
    external: true