services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ../../secrets/devops/grafana/grafana-secrets.txt
    networks:
      - bridge-network
    depends_on:
      - prometheus
    restart: always

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - prometheus-data:/prometheus
      - ./prometheus/global/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/rules/alert.rules.yml:/etc/prometheus/alert.rules.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=30d'         # Keep data for 30 days
      - '--storage.tsdb.retention.size=10GB'        # Or until 10GB max (whichever comes first)
      - '--storage.tsdb.path=/prometheus'           # Local path for DB files
      - '--storage.tsdb.wal-compression'            # Compress WAL to save disk
    ports:
      - 9090:9090
    networks:
      - bridge-network
    depends_on:
      - alertmanager
    restart: always

  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    ports:
      - "9093:9093"
    volumes:
      - alertmanager-data:/alertmanager
      - ./alertmanager/config/slack-alertmenager.yml:/etc/alertmanager/config/slack-alertmenager.yml
      - ./alertmanager/template/alert.tmpl:/etc/alertmanager/template/alert.tmpl
    command:
      - '--config.file=/etc/alertmanager/config/slack-alertmenager.yml'
    networks:
      - bridge-network
    restart: always

  node_exporter:
    image: prom/node-exporter
    container_name: node_exporter
    ports:
      - "9100:9100"
    networks:
      - bridge-network
    restart: always

volumes:
  prometheus-data:
  alertmanager-data:

networks:
  bridge-network:
    name: transcendence_bridge-network
    external: true