
groups:
  - name: alert.rules
    rules:
      - alert: InstanceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Instance down: {{ $labels.instance }}"
          description: "The target {{ $labels.instance }} (job: {{ $labels.job }}) has been unreachable for over 1 minute."

      - alert: HighCPUUsage
        expr: rate(process_cpu_seconds_total[1m]) > 0.9
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage on {{ $labels.instance }}"
          description: "The process is consuming > 90% of a single CPU core for over 1 minute."

      - alert: HighMemoryUsage
        expr: process_resident_memory_bytes > 500000000  # Adjust based on your app's normal usage
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage on {{ $labels.instance }}"
          description: "Process is using more than 500MB of memory."

      - alert: HeapMemoryLeak
        expr: nodejs_heap_size_used_bytes / nodejs_heap_size_total_bytes > 0.9
        for: 3m
        labels:
          severity: critical
        annotations:
          summary: "Possible memory leak on {{ $labels.instance }}"
          description: "Heap memory usage > 90% for over 3 minutes. Might be a leak."

      - alert: EventLoopLagHigh
        expr: nodejs_eventloop_lag_max_seconds > 0.05
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "High event loop lag on {{ $labels.instance }}"
          description: "Node.js event loop lag > 50ms. App may be struggling with blocking I/O or heavy CPU work."

      - alert: GCSpikeDetected
        expr: rate(nodejs_gc_duration_seconds_sum[1m]) > 0.1
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "GC duration spike on {{ $labels.instance }}"
          description: "Garbage collection taking unusually long. GC rate > 100ms/s."

      - alert: TooManyOpenFileDescriptors
        expr: process_open_fds / process_max_fds > 0.8
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High file descriptor usage on {{ $labels.instance }}"
          description: "More than 80% of allowed file descriptors in use. Might lead to 'EMFILE' errors."
